src/Cake.Issues.Markdownlint/MarkdownlintIssuesAliases.cs
Add MarkdownlintIssuesProviderTypeName alias
Fixes #2
=> (GH-2) Add MarkdownlintIssuesProviderTypeName alias

nuspec/nuget/Cake.Issues.Markdownlint.nuspec, src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint.Tests/packages.config, src/Cake.Issues.Markdownlint.sln, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/packages.config
Build against Cake 0.26 and Cake.Issues 0.2.0
Also updates XUnit to 2.3.1 and Shouldly to 3.0.0
Fixes #9
Fixes #11
=> Update to Cake.Issues 0.2.0 

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint.Tests/Markdownlint/MarkdownlintIssuesProviderTests.cs, src/Cake.Issues.Markdownlint.Tests/MarkdownlintCli/MarkdownlintCliIssuesProviderTests.cs, src/Cake.Issues.Markdownlint.Tests/packages.config, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/Markdownlint/MarkdownlintIssuesProvider.cs, src/Cake.Issues.Markdownlint/MarkdownlintCli/MarkdownlintCliIssuesProvider.cs, src/Cake.Issues.Markdownlint/packages.config
Update to Cake.Issues 0.3.0
Fixes #15
=> (GH-15) Update to Cake.Issues 0.3.0

tools/packages.config
Build with Cake 0.29.0
Fixes #22
=> (GH-22) Build with Cake 0.29.0

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint.Tests/packages.config, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/packages.config
Update Cake.Issues to 0.4.0-beta.1
Fixes #24
=> (GH-24) Update Cake.Issues to 0.4.0-beta.1

src/Cake.Issues.Markdownlint.Tests/MarkdownlintRuleUrlResolverTests.cs, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/MarkdownlintIssuesAliases.cs, src/Cake.Issues.Markdownlint/MarkdownlintRuleDescription.cs, src/Cake.Issues.Markdownlint/MarkdownlintRuleUrlResolver.cs
Add alias for custom rule url resolver registration
Fixes #27
=> (GH-27) Add alias for custom rule url resolver registration

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint.Tests/packages.config, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/packages.config
Update to Cake.Issues 0.6.0 Beta 1
Fixes #32
=> (GH-32) Update to Cake.Issues 0.6.0 Beta 1

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint.Tests/LogFileFormat/MarkdownlintCliLogFileFormatTests.cs, src/Cake.Issues.Markdownlint.Tests/MarkdownlintIssuesSettingsTests.cs, src/Cake.Issues.Markdownlint.Tests/packages.config, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/packages.config
=> Add test case with empty file

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj
=> Update XUnit to 2.4.1

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj
Build against Cake 0.33.0
Fixes #49
=> (GH-49) Build against Cake 0.33.0

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint.Tests/LogFileFormat/MarkdownlintCliLogFileFormatTests.cs, src/Cake.Issues.Markdownlint.Tests/LogFileFormat/MarkdownlintLogFileFormatTests.cs, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintLogFileFormat.cs
Update to Cake.Issues 0.7.0-beta001 
Fixes #50
=>  (GH-50) Update to Cake.Issues 0.7.0-beta001 

README.md, nuspec/nuget/Cake.Issues.Markdownlint.nuspec
Website changed to cakeissues.net
Fixes #66
=> (GH-66) Change website to cakeissues.net

src/Cake.Issues.Markdownlint/MarkdownlintIssuesAliases.IssueProvider.cs, src/Cake.Issues.Markdownlint/MarkdownlintIssuesProvider.cs
Make issue provider type name available on issue provider
Fixes #73
=> (GH-73) Make issue provider type name available on issue provider

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintCliLogFileFormat.cs, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintLogFileFormat.cs
Update Cake.Issues to 0.8.0
Fixes #82
=> (GH-82) Update to Cake.Issues 0.8.0

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint.Tests/LogFileFormat/MarkdownlintCliLogFileFormatTests.cs, src/Cake.Issues.Markdownlint.Tests/Testfiles/MarkdownlintCliLogFileFormat/markdownlint-cli-0.19.0.log, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintCliLogFileFormat.cs
=> (GH-90) Support markdownlint-cli 0.19.0 log file format

src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintCliLogFileFormat.cs
Use named groupes for parsing markdownlint-cli log file
=> Use named groupes for parsing

docs/features.md, src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintCliLogFileFormat.cs, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintLogFileFormat.cs
Update to Cake.Issues 0.9.0 Beta 2
Fixes #114
=> (GH-114) Update to Cake.Issues 0.9.0 Beta 2

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj
Build against Cake.Issues 1.0 beta 1
=> Build against Cake.Issues 1.0 beta 1

docs/features.md, src/Cake.Issues.Markdownlint.Tests/LogFileFormat/MarkdownlintCliLogFileFormatTests.cs, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintCliLogFileFormat.cs
Report column information if available for MarkdownlintCliLogFileFormat
Fixes #164
=> (GH-164) Report column information if available for MarkdownlintCliLogFileFormat

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj
Builds against Cake 2.0
Fixes #175
Fixes #182
=> (GH-175) Build against Cake 2.0

src/Cake.Issues.Markdownlint.sln
Update solution to Visual Studio 2022
=> Update solution to Visual Studio 2022

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint/BaseMarkdownlintLogFileFormat.cs, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintCliLogFileFormat.cs
Update to Cake.Issues 2.0 Beta 2
=> Update to Cake.Issues 2.0 Beta 2

.appveyor.yml, nuspec/nuget/Cake.Issues.Markdownlint.nuspec, src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj
Updates target frameworks to .NET 6 and .NET 7.
Fixes #206
=> (GH-206) Update target frameworks

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintCliLogFileFormat.cs, tests/.config/dotnet-tools.json
Updates to Cake 3.0 and Cake.Issues 3.0 Beta 1
Fixes #207 
Fixes #208
=> Update to Cake 3.0 and Cake.Issues 3.0 Beta 1

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint.Tests/LogFileFormat/MarkdownlintCliLogFileFormatTests.cs, src/Cake.Issues.Markdownlint.Tests/Testfiles/MarkdownlintCliLogFileFormat/markdownlint-cli-0.35.0.log
Add test case for MarkdownLintCliLogFileFormat for files generated with markdownlint-cli 0.35.0
=> Add test case for markdownlint-cli 0.35.0

.appveyor.yml, azure-pipelines.yml, nuspec/nuget/Cake.Issues.Markdownlint.nuspec, src/Cake.Issues.Markdownlint.Tests/MarkdownlintIssuesSettingsTests.cs, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj, src/Cake.Issues.Markdownlint/IssueDataContract.cs, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintCliJsonLogFileFormat.cs, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintCliLogFileFormat.cs, src/Cake.Issues.Markdownlint/LogFileFormat/MarkdownlintV1LogFileFormat.cs, src/Cake.Issues.Markdownlint/MarkdownlintIssuesProvider.cs, src/Directory.Build.props
Multi-Target .NET 8
Fixes #246
=> Multi-Target .NET 8

src/Cake.Issues.Markdownlint.Tests/Cake.Issues.Markdownlint.Tests.csproj, src/Cake.Issues.Markdownlint/Cake.Issues.Markdownlint.csproj
Update Cake.Issues to 4.0.0-beta0001
Fixes #248
=> Update Cake.Issues to 4.0.0-beta0001

.appveyor.yml
Update .NET SDK version used in AppVeyor build
=> Update .NET SDK version used in AppVeyor build

azure-pipelines.yml, global.json, tests/global.json
=> Add global.json
